// vademecumData.js

// 1. OPCIONES LEGALES Y NORMATIVAS (CHILE - ISP DS 466, 404, 405)
export const OPCIONES_DESPLEGABLES = {
  condicionVenta: [
    "Venta Directa",
    "Receta Médica",
    "Receta Médica Retenida",
    "Receta Cheque"
  ],
  listaControl: [
    "N/A",
    "Lista I",
    "Lista II",
    "Lista III",
    "Lista IV",
    "Control de Precursores"
  ]
};

// 2. BLOQUE I: NEUROLÓGICO, CARDIOVASCULAR Y ESPECÍFICOS
export const BLOQUE_I = [
  {
    nombre: "Fenitoína 100 mg",
    principio_activo: "Fenitoína Sódica",
    categoria: "Anticonvulsivante / Antiepiléptico",
    para_que_sirve: "Control preventivo de convulsiones tónico-clónicas generalizadas (gran mal) y crisis parciales complejas. Frecuentemente prescrito en neurocirugía o traumatismos craneales severos para prevenir episodios epilépticos post-quirúrgicos.",
    posologia: "Dosis médica estrictamente individualizada basada en niveles plasmáticos. Habitualmente en adultos: 100 mg por vía oral 2 a 3 veces al día. Se recomienda administrar junto con alimentos para minimizar la irritación gástrica.",
    contraindicaciones: "Pacientes con bradicardia sinusal, bloqueo auriculoventricular de segundo y tercer grado o síndrome de Stokes-Adams. Riesgo severo de teratogenicidad en embarazo (Síndrome de hidantoína fetal).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Consejo clínico vital: La hiperplasia gingival (crecimiento y sangrado excesivo de las encías) es un efecto secundario crónico muy común. El paciente debe mantener una higiene bucal impecable y visitar al dentista regularmente.",
    cross_selling: "Cepillos dentales de cerdas ultrasuaves (quirúrgicos), pastas dentales para encías sangrantes y colutorios con Clorhexidina al 0.12%."
  },
  {
    nombre: "Carbamazepina 200 mg",
    principio_activo: "Carbamazepina",
    categoria: "Antiepiléptico / Estabilizador del Ánimo",
    para_que_sirve: "Tratamiento de primera línea para crisis epilépticas parciales (con o sin generalización secundaria), neuralgia del trigémino (dolor facial agudo) y profilaxis del trastorno bipolar en pacientes que no responden al litio.",
    posologia: "Dosis inicial sugerida en epilepsia: 200 mg 1 o 2 veces al día. En neuralgia del trigémino, se inicia con 100-200 mg al día. Las dosis deben aumentarse gradualmente según respuesta clínica. Tomar durante o después de las comidas con líquido.",
    contraindicaciones: "Antecedentes de depresión de la médula ósea, porfiria aguda intermitente y uso concomitante o reciente (últimos 14 días) con inhibidores de la MAO (IMAO).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Fuerte inductor enzimático hepático: Acelera el metabolismo de otros fármacos, reduciendo su eficacia (ej. anula el efecto de los anticonceptivos orales). El paciente debe usar métodos de barrera adicionales.",
    cross_selling: "Preservativos (si la paciente usa anticoncepción oral), lágrimas artificiales (puede causar visión borrosa inicialmente)."
  },
  {
    nombre: "Gabapentina 300 mg",
    principio_activo: "Gabapentina",
    categoria: "Neuromodulador / Antiepiléptico Analgésico",
    para_que_sirve: "Tratamiento específico del dolor neuropático periférico intenso (como neuropatía diabética dolorosa o neuralgia postherpética) y terapia adyuvante en adultos y adolescentes con epilepsia parcial.",
    posologia: "Titulación médica escalonada para evitar somnolencia severa: Día 1: 300 mg una vez al día. Día 2: 300 mg dos veces al día. Día 3: 300 mg tres veces al día (dosis de mantenimiento habitual 900 mg/día).",
    contraindicaciones: "Hipersensibilidad conocida al principio activo. Requiere ajuste de dosis estricto (reducción) en pacientes con insuficiencia renal o hemodiálisis.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Advertir al paciente sobre la somnolencia profunda y los mareos durante la primera semana de titulación. El cuerpo suele generar tolerancia en unos 10 días, por lo que no debe abandonar el tratamiento prematuramente.",
    cross_selling: "Complejo vitamínico B (Neurobionta) para potenciar la recuperación de la vaina de mielina del nervio dañado."
  },
  {
    nombre: "Levetiracetam 500 mg",
    principio_activo: "Levetiracetam",
    categoria: "Antiepiléptico de Nueva Generación",
    para_que_sirve: "Terapia de amplio espectro, utilizada como monoterapia o terapia combinada en convulsiones de inicio parcial, mioclónicas o tónico-clónicas primarias generalizadas. Destaca por su alta eficacia clínica.",
    posologia: "Dosis inicial recomendada en adultos: 500 mg dos veces al día. Según la respuesta clínica, la dosis puede incrementarse hasta 1500 mg dos veces al día. Puede tomarse con o sin alimentos.",
    contraindicaciones: "Hipersensibilidad a derivados de la pirrolidona. Precaución especial en pacientes con antecedentes de depresión severa o ideación suicida.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Ventaja terapéutica: A diferencia de los antiepilépticos clásicos (Fenitoína, Carbamazepina), el Levetiracetam casi no presenta interacciones medicamentosas a nivel hepático. Sin embargo, puede inducir irritabilidad o cambios de humor notables.",
    cross_selling: "No requiere suplementación específica. Importante: Sugerir mantener siempre la misma marca (original o bioequivalente), ya que los cambios de laboratorio pueden desestabilizar a pacientes neurológicamente sensibles."
  },
  {
    nombre: "Sumatriptán 50 mg",
    principio_activo: "Sumatriptán Succinato",
    categoria: "Agonista selectivo de Serotonina (5-HT1) / Antimigrañoso",
    para_que_sirve: "Tratamiento de rescate agudo y rápido de las crisis de migraña (jaqueca) con o sin aura. Funciona contrayendo los vasos sanguíneos dilatados del cerebro. NO es un medicamento preventivo o profiláctico.",
    posologia: "1 comprimido (50 mg o 100 mg) lo más pronto posible tras el inicio del dolor de cabeza. Si la migraña cede pero reaparece, puede tomarse una segunda dosis tras 2 horas. Dosis máxima: 300 mg en 24 horas.",
    contraindicaciones: "Absolutamente contraindicado en enfermedad isquémica cardíaca (infarto previo, angina), hipertensión arterial no controlada y uso concomitante con Ergotamina (Migranol).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Educación de mesón crítica: ¡La oportunidad es todo! El paciente debe tomarlo al primer síntoma del aura o dolor. Si se toma cuando la migraña ya alcanzó su peak de dolor y náuseas, su efectividad disminuye drásticamente.",
    cross_selling: "Antieméticos (Domperidona) para las náuseas asociadas a la migraña severa, antifaces de gel frío para alivio local."
  },
  {
    nombre: "Ergotamina + Cafeína (Migranol / Cefalmin)",
    principio_activo: "Tartrato de Ergotamina 1 mg + Cafeína 100 mg",
    categoria: "Antimigrañoso Vasoconstrictor",
    para_que_sirve: "Tratamiento sintomático clásico para abortar crisis agudas de migraña tensional o vascular que no responden a analgésicos comunes.",
    posologia: "Dosis de ataque: 1 a 2 comprimidos al inicio de la crisis. Si el dolor persiste, se puede administrar 1 comprimido adicional cada 30 minutos. Límite estricto: Máximo 6 comprimidos en 24 horas y 10 por semana.",
    contraindicaciones: "Embarazo (riesgo de aborto por contracción uterina), lactancia, hipertensión severa, enfermedad vascular periférica (riesgo de isquemia) y falla hepática/renal.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Advertencia Farmacológica (Ojo de lince): El uso frecuente o diario de Ergotamina genera 'Cefalea de Rebote'. El paciente entra en un círculo vicioso donde el fármaco que alivia el dolor, provoca la siguiente migraña por abstinencia.",
    cross_selling: "Medicamentos gástricos (Metoclopramida) en caso de que la migraña provoque emesis (vómitos) que impida la absorción oral."
  },
  {
    nombre: "Levodopa + Carbidopa (250/25 mg)",
    principio_activo: "Levodopa + Carbidopa",
    categoria: "Antiparkinsoniano (Precursor de Dopamina)",
    para_que_sirve: "Terapia de sustitución fundamental para el control sintomático de la Enfermedad de Parkinson idiopática. Mejora la rigidez muscular, la bradicinesia (lentitud) y el temblor en reposo.",
    posologia: "Dosis escalonada estrictamente por el neurólogo. Habitualmente se distribuye en 3 o 4 tomas diarias para mantener niveles estables de dopamina y evitar fluctuaciones motoras (efecto on-off).",
    contraindicaciones: "Pacientes con glaucoma de ángulo estrecho no tratado, lesiones cutáneas sospechosas de melanoma (puede activarlo) y uso concomitante con IMAO no selectivos.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Interacción Alimentaria Clave: Los aminoácidos de las proteínas (carnes, lácteos, huevos) compiten con la Levodopa para absorberse en el intestino. Aconsejar al paciente tomar la pastilla 30 a 60 minutos antes de las comidas principales.",
    cross_selling: "Suplementación nutricional o espesantes de líquidos para adultos mayores si presentan disfagia (dificultad para tragar) asociada al Parkinson avanzado."
  },
  {
    nombre: "Donepezilo 10 mg",
    principio_activo: "Donepezilo Clorhidrato",
    categoria: "Inhibidor reversible de la Acetilcolinesterasa",
    para_que_sirve: "Tratamiento sintomático paliativo del deterioro cognitivo (memoria y conducta) en la enfermedad de Alzheimer de intensidad leve a moderadamente grave. No cura ni detiene la progresión de la enfermedad.",
    posologia: "Inicio con 5 mg/día durante al menos 4 semanas (para evaluar tolerancia gástrica), aumentando luego a la dosis de mantención de 10 mg/día. Se administra en una toma única por la noche, antes de acostarse.",
    contraindicaciones: "Hipersensibilidad a derivados de piperidina. Requiere precaución extrema en pacientes con antecedentes de úlceras gástricas, asma severa o alteraciones de la conducción cardíaca (bradicardia).",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "N/A",
    tips_venta: "Información al cuidador: Al inicio del tratamiento, es común que el paciente experimente pesadillas, sueños vívidos o náuseas matutinas. Estos efectos suelen ser transitorios y disminuyen con las semanas.",
    cross_selling: "Suplementos nutricionales hipercalóricos (Ensure Advance) debido a que la pérdida de apetito y de peso son comunes en etapas medias del Alzheimer."
  },
  {
    nombre: "Hidróxido de Magnesio / Aluminio",
    principio_activo: "Hidróxido de Magnesio + Hidróxido de Aluminio",
    categoria: "Antiácido Neutralizante de Acción Local",
    para_que_sirve: "Alivio rápido y sintomático de la hiperacidez gástrica, ardor de estómago (pirosis), indigestión ácida y dispepsia. Actúa tamponando químicamente el ácido clorhídrico ya presente en el estómago.",
    posologia: "1 a 2 cucharadas (suspensión) o 1 a 2 comprimidos masticables administrados entre las comidas (1 a 3 horas después de comer) y al acostarse.",
    contraindicaciones: "Insuficiencia renal grave (riesgo de toxicidad por acumulación de aluminio). Contraindicado en dolor abdominal agudo no diagnosticado o sospecha de apendicitis.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Interacción farmacológica crítica: Estos antiácidos son como un 'imán' en el estómago. Atrapan y reducen la absorción de otros fármacos (Especialmente Fierro, Levotiroxina, y antibióticos como Ciprofloxacino). Debe existir un espacio de 2 HORAS entre la toma del antiácido y cualquier otro medicamento.",
    cross_selling: "Inhibidores de bomba (Omeprazol) de venta libre (dosis bajas) si el paciente presenta acidez recurrente más de 3 días a la semana."
  },
  {
    nombre: "Buscapina (Hioscina) 10 mg",
    principio_activo: "Butilbromuro de Hioscina",
    categoria: "Antiespasmódico (Anticolinérgico Periférico)",
    para_que_sirve: "Alivio efectivo de los espasmos agudos del tracto gastrointestinal (cólicos estomacales/intestinales), vías biliares (cólico biliar) y vías genitourinarias (cólicos nefríticos o menstruales severos).",
    posologia: "Adultos y niños mayores de 6 años: 1 a 2 comprimidos recubiertos, 3 a 5 veces al día, ingeridos enteros con abundante líquido. No masticar.",
    contraindicaciones: "Miastenia gravis, megacolon, glaucoma de ángulo estrecho no tratado, retención urinaria por hipertrofia prostática e íleo paralítico.",
    condicion_venta: "Venta Directa / Receta Médica (Según presentación/asociación)",
    lista_control: "N/A",
    tips_venta: "Efectos anticolinérgicos: Informar al paciente que puede experimentar sequedad de boca, visión ligeramente borrosa y disminución del sudor. No confundir con la 'Buscapina Compuesta' o 'Femin', las cuales traen analgésico añadido (Paracetamol o Ibuprofeno).",
    cross_selling: "Té o infusiones digestivas antiespasmódicas (Manzanilla, Melisa), guateros de agua o gel para aplicar calor local en la zona del cólico."
  },
  {
    nombre: "Insulina Cristalina (Rápida)",
    principio_activo: "Insulina Humana Regular (Acción Rápida)",
    categoria: "Antidiabético Inyectable",
    para_que_sirve: "Regulación aguda del metabolismo de la glucosa en pacientes con Diabetes Mellitus tipo 1 y tipo 2. Su inicio de acción es de 30 minutos y su peak máximo ocurre entre 2 a 4 horas post-inyección.",
    posologia: "Inyección subcutánea indicada estrictamente por el médico. Debe administrarse entre 15 a 30 minutos ANTES de una comida que contenga carbohidratos.",
    contraindicaciones: "Episodios de hipoglicemia actual. Hipersensibilidad a la insulina humana.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Regla visual de Farmacia: La Insulina Cristalina (Rápida) debe ser completamente transparente como el agua. Si está turbia o presenta grumos, se debe desechar. Requiere cadena de frío estricta (2°C a 8°C) antes de abrir. Una vez en uso, dura 28 días a temperatura ambiente fresca.",
    cross_selling: "Jeringas de insulina de precisión, agujas para lápiz (si usa Pen), toallitas prepadas con alcohol isopropílico, contenedor rígido para descarte de material cortopunzante."
  },
  {
    nombre: "Probióticos Multicepa / S. Boulardii",
    principio_activo: "Bacterias Lácticas (Lactobacillus, Bifidobacterium) o Levadura (Saccharomyces Boulardii)",
    categoria: "Restaurador de la Flora Intestinal / Antidiarreico Biológico",
    para_que_sirve: "Prevención y tratamiento de diarreas agudas, reducción de la diarrea asociada a la toma de antibióticos, y estabilización del microbioma en pacientes con Síndrome de Intestino Irritable.",
    posologia: "1 a 2 cápsulas o sobres al día. Disolver en líquidos a temperatura ambiente. Jamás administrar con bebidas o comidas muy calientes, ya que el calor destruye los microorganismos vivos.",
    contraindicaciones: "Pacientes gravemente inmunodeprimidos (VIH avanzado no tratado, quimioterapia agresiva) o portadores de catéter venoso central (riesgo de fungemia o bacteriemia sistémica).",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Protocolo de Antibióticos: Si el paciente está tomando Amoxicilina o Ciprofloxacino, el S. Boulardii (levadura/hongo) es ideal porque el antibiótico no lo mata. Si lleva un probiótico bacteriano (Lactobacillus), recuérdale que debe tomarlo con al menos 3 horas de diferencia del antibiótico.",
    cross_selling: "Sales de rehidratación oral (sueros) en caso de cuadro diarreico activo."
  },
  {
    nombre: "Atropina + Difenoxilato",
    principio_activo: "Sulfato de Atropina + Clorhidrato de Difenoxilato",
    categoria: "Antidiarreico de Acción Central (Opioide sintético + Anticolinérgico)",
    para_que_sirve: "Tratamiento farmacológico sintomático de apoyo en diarreas agudas y crónicas severas, reduciendo la motilidad (movimiento) propulsiva del intestino.",
    posologia: "Dosis de ataque en adultos: 2 comprimidos, 3 a 4 veces al día (hasta frenar el cuadro). Una vez controlado, la dosis debe reducirse inmediatamente. No recomendado para uso prolongado.",
    contraindicaciones: "Niños pequeños. Contraindicación absoluta en diarreas con sangre causadas por bacterias invasivas (Salmonella, Shigella, C. difficile) ya que detener el tránsito intestinal empeora la infección al retener las toxinas.",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "N/A",
    tips_venta: "Mecanismo dual: El Difenoxilato frena la diarrea, pero al ser un derivado opioide, puede causar adicción en dosis altas. Se le añade una dosis subclínica de Atropina para provocar efectos desagradables (taquicardia, boca seca) si el paciente intenta abusar del fármaco.",
    cross_selling: "Toallitas húmedas para adultos y cremas protectoras de óxido de zinc (por el daño y ardor perianal asociado a diarreas líquidas severas)."
  },
  {
    nombre: "Mebeverina 200 mg",
    principio_activo: "Mebeverina Clorhidrato",
    categoria: "Antiespasmódico Musculotropo Selectivo",
    para_que_sirve: "Alivio sintomático de espasmos gastrointestinales secundarios a enfermedades orgánicas, y tratamiento específico del dolor abdominal, calambres y alteraciones del tránsito en el Síndrome del Intestino Irritable (SII).",
    posologia: "1 cápsula de liberación prolongada (200 mg) administrada 2 veces al día, preferentemente 20 minutos antes del desayuno y la cena. Tragar entera sin masticar.",
    contraindicaciones: "Hipersensibilidad al principio activo. Precaución y evaluación médica en caso de íleo paralítico o megacolon tóxico.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Perfil de seguridad superior: A diferencia de la Hioscina (Buscapina) o la Pargeverina (Viadil), la Mebeverina actúa directamente relajando el músculo liso intestinal sin afectar el sistema nervioso autónomo, por lo que NO causa los molestos efectos secundarios de boca seca, retención de orina o visión borrosa.",
    cross_selling: "Simeticona masticable para aliviar la hinchazón o meteorismo (gases) frecuentemente asociado al colon irritable."
  },
  {
    nombre: "Clonixinato de Lisina 125 mg",
    principio_activo: "Clonixinato de Lisina",
    categoria: "AINE / Analgésico Potente",
    para_que_sirve: "Tratamiento de acción rápida para el dolor somático y visceral de intensidad leve a moderada. Ampliamente prescrito en odontalgias (dolor de muelas), mialgias severas, dolores articulares agudos y dismenorrea (dolor menstrual).",
    posologia: "1 a 2 comprimidos (125-250 mg) cada 6 a 8 horas, dependiendo de la intensidad del dolor. Dosis máxima diaria: 6 comprimidos (750 mg). Tomar con abundante agua junto con las comidas.",
    contraindicaciones: "Úlcera gastroduodenal activa, hemorragia digestiva reciente, asma severo asociado a sensibilidad a AINEs, insuficiencia renal o hepática severa.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Fármaco de muy alta rotación en el mostrador (conocido comercialmente como Nefersil). Es muy efectivo, pero es uno de los analgésicos más gastrolesivos. Advertir al paciente no tomarlo con el estómago vacío.",
    cross_selling: "Protector gástrico (Omeprazol o Famotidina) en terapias mayores a 3 días. Compresas térmicas de gel para inflamaciones musculoesqueléticas."
  },
  {
    nombre: "Amiodarona 200 mg",
    principio_activo: "Amiodarona Clorhidrato",
    categoria: "Antiarrítmico de Clase III",
    para_que_sirve: "Fármaco de alta complejidad utilizado para la profilaxis y tratamiento de arritmias ventriculares graves (con riesgo vital), fibrilación auricular y taquicardias supraventriculares asociadas al Síndrome de Wolff-Parkinson-White.",
    posologia: "Dosificación estrictamente controlada por el cardiólogo. Suele requerir una dosis de carga inicial alta (600 mg/día) seguida de una dosis de mantención ajustada a la mínima efectiva (100-200 mg/día).",
    contraindicaciones: "Bradicardia sinusal severa, bloqueo auriculoventricular sin marcapasos, disfunción tiroidea previa y sensibilidad conocida al yodo.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Precaución Dermatológica: Provoca fotosensibilidad extrema. La exposición directa al sol puede causar severas quemaduras solares o una coloración gris-azulada irreversible en la piel expuesta. Contiene altas cantidades de Yodo, afectando la tiroides.",
    cross_selling: "Bloqueador solar dermatológico FPS 50+ de amplio espectro (UVA/UVB) de uso diario y estricto."
  },
  {
    nombre: "Digoxina 0.25 mg",
    principio_activo: "Digoxina (Glucósido digitálico)",
    categoria: "Cardiotónico / Inotrópico Positivo",
    para_que_sirve: "Mejora la fuerza de contracción del músculo cardíaco. Utilizada principalmente en el tratamiento de la insuficiencia cardíaca crónica y para ralentizar la frecuencia ventricular en pacientes con fibrilación auricular.",
    posologia: "Fármaco de margen terapéutico muy estrecho. Dosis de mantenimiento en adultos varía entre 0.125 mg a 0.25 mg al día, regulada mediante exámenes de niveles séricos de digoxina.",
    contraindicaciones: "Bloqueo auriculoventricular intermitente o completo, miocardiopatía hipertrófica obstructiva, taquicardia o fibrilación ventricular.",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "N/A",
    tips_venta: "Signos de alerta vital (Intoxicación Digitálica): Si el paciente adulto mayor en mostrador reporta pérdida brusca de apetito, náuseas y vómitos intensos, o alteraciones visuales como ver 'halos amarillos o verdes' alrededor de las luces, derivar a Urgencias de inmediato.",
    cross_selling: "No se recomienda venta cruzada. Requiere un monitoreo clínico muy cerrado."
  },
  {
    nombre: "Gemfibrozilo 600 mg",
    principio_activo: "Gemfibrozilo",
    categoria: "Hipolipemiante (Derivado del ácido fíbrico)",
    para_que_sirve: "Tratamiento de la hipertrigliceridemia severa (niveles peligrosamente altos de triglicéridos) y dislipidemia mixta, especialmente para prevenir el riesgo de pancreatitis aguda secundaria a esta condición.",
    posologia: "1200 mg diarios divididos en dos tomas: 600 mg media hora ANTES del desayuno y 600 mg media hora ANTES de la cena.",
    contraindicaciones: "Insuficiencia hepática severa, enfermedad preexistente de la vesícula biliar (cálculos) e insuficiencia renal grave. Precaución extrema al coadministrar con estatinas.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Interacción de riesgo: Si el paciente compra Gemfibrozilo junto con Atorvastatina (u otra estatina), advertir que esta combinación eleva el riesgo de daño muscular grave (rabdomiólisis). Si presentan dolor muscular agudo o debilidad, deben contactar a su médico. Recordar tomar siempre con estómago vacío.",
    cross_selling: "Suplementos de Omega 3 de alta pureza (coadyuvantes en la reducción de triglicéridos) previa validación médica."
  },
  {
    nombre: "Fenofibrato 160 mg",
    principio_activo: "Fenofibrato",
    categoria: "Hipolipemiante Fibrato de Nueva Generación",
    para_que_sirve: "Reducción de niveles elevados de colesterol total, LDL, apolipoproteína B y triglicéridos, al mismo tiempo que aumenta el colesterol HDL (bueno). Utilizado cuando las dietas y el ejercicio no son suficientes.",
    posologia: "1 comprimido o cápsula de 160 mg al día. Las cápsulas deben tragarse enteras con un vaso de agua y SIEMPRE junto con la comida principal para asegurar una óptima absorción.",
    contraindicaciones: "Enfermedad hepática o renal severa, colecistopatía (enfermedades de la vesícula), pancreatitis crónica o aguda (excepto la causada por triglicéridos altos).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "A diferencia del Gemfibrozilo (que se toma con el estómago vacío), el Fenofibrato requiere la presencia de alimentos en el estómago para absorberse correctamente. Es más seguro que el Gemfibrozilo cuando el médico decide combinarlo con una estatina.",
    cross_selling: "Tensiómetro digital (muchos pacientes dislipidémicos padecen Síndrome Metabólico e hipertensión)."
  },
  {
    nombre: "Clopidogrel 75 mg",
    principio_activo: "Clopidogrel Bisulfato",
    categoria: "Antiagregante Plaquetario Profiláctico",
    para_que_sirve: "Inhibe la formación de coágulos en la sangre. Esencial en la prevención secundaria de eventos aterotrombóticos (infartos agudos al miocardio, accidentes cerebrovasculares isquémicos) y crucial en pacientes con stents cardíacos implantados.",
    posologia: "Dosis estándar de mantenimiento: 1 comprimido de 75 mg una vez al día, con o sin alimentos.",
    contraindicaciones: "Hemorragia patológica activa (como úlcera péptica sangrante o hemorragia intracraneal), insuficiencia hepática grave.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Interacción crítica de mostrador: El Clopidogrel es un profármaco que necesita activarse en el hígado. Fármacos como el Omeprazol y el Esomeprazol bloquean esta activación, anulando el efecto anticoagulante y dejando al paciente en riesgo de infarto. Si compran protector gástrico, el seguro suele ser Pantoprazol o Famotidina.",
    cross_selling: "Aspirina de 100 mg (Aspirina EC) ya que la Terapia Antiagregante Dual (Clopidogrel + Aspirina) es un estándar médico muy frecuente posterior a un evento cardíaco."
  }
];

// 3. BLOQUE II: RESPIRATORIO, ANTIINFECCIOSOS, DERMATOLÓGICOS Y UROLÓGICOS
export const BLOQUE_II = [
  {
    nombre: "Metilfenidato 10 mg",
    principio_activo: "Metilfenidato Clorhidrato",
    categoria: "Estimulante del Sistema Nervioso Central",
    para_que_sirve: "Tratamiento del Trastorno por Déficit de Atención e Hiperactividad (TDAH) y, en casos específicos, narcolepsia. Mejora la atención y reduce la impulsividad.",
    posologia: "Dosis estrictamente individualizada por el psiquiatra o neurólogo. Habitualmente se inicia con 10 mg 2 o 3 veces al día (desayuno y almuerzo). No administrar después de las 18:00 hrs para evitar insomnio.",
    contraindicaciones: "Ansiedad severa, agitación, glaucoma, síndrome de Tourette, hipertensión arterial severa y uso concomitante con IMAO.",
    condicion_venta: "Receta Cheque",
    lista_control: "Lista II",
    tips_venta: "Control Legal Estricto: Solo se dispensa con Receta Cheque (talón amarillo/marrón/rojo según MINSAL). No se puede fraccionar bajo ninguna circunstancia. Revisar que la receta esté dentro de los 30 días de vigencia.",
    cross_selling: "No aplica venta cruzada por ley. Se puede ofrecer apoyo con organización de pastillas semanal para cuidadores."
  },
  {
    nombre: "Bromhexina 8 mg/5 ml Jarabe",
    principio_activo: "Clorhidrato de Bromhexina",
    categoria: "Mucolítico / Expectorante",
    para_que_sirve: "Fluidifica y reduce la viscosidad de las secreciones bronquiales espesas, facilitando su expulsión mediante la tos en bronquitis, asma y afecciones respiratorias con dificultad de expectoración.",
    posologia: "Adultos y niños mayores de 10 años: 10 ml (8 mg) 3 veces al día. Niños de 5 a 10 años: 5 ml 3 veces al día. Agitar antes de usar.",
    contraindicaciones: "Úlcera gástrica activa (precaución), hipersensibilidad al fármaco. No usar en tos seca improductiva.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Consejo de mesón clave: El medicamento por sí solo no 'saca' la flema. Debes instruir al paciente a beber al menos 2 litros de agua al día; la hidratación es el mejor mucolítico que existe.",
    cross_selling: "Vitamina C efervescente, miel de abeja pura o pastillas para la garganta con miel y limón."
  },
  {
    nombre: "Oximetazolina 0.05% Spray Nasal",
    principio_activo: "Clorhidrato de Oximetazolina",
    categoria: "Descongestionante Nasal Tópico (Alfa-agonista)",
    para_que_sirve: "Alivio rápido y temporal de la congestión nasal severa asociada a resfriados, rinitis alérgica o sinusitis.",
    posologia: "1 a 2 aplicaciones en cada fosa nasal, cada 10 a 12 horas. No exceder las 2 aplicaciones diarias por fosa.",
    contraindicaciones: "Glaucoma de ángulo estrecho, hipertensión arterial severa, hipertiroidismo y pacientes en tratamiento con IMAO.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "¡Alerta de Rinitis Medicamentosa! Advertir al paciente que este spray es solo para 'salir del paso' (máximo 3 a 5 días). Si se usa en exceso, provoca un efecto rebote que tapa la nariz crónicamente y daña la mucosa.",
    cross_selling: "Lavados nasales con Suero Fisiológico 0.9% o sprays de Agua de Mar (hipertónica o isotónica) para higiene diaria sin efecto rebote."
  },
  {
    nombre: "Cefalexina 500 mg",
    principio_activo: "Cefalexina Monohidrato",
    categoria: "Antibiótico (Cefalosporina de 1ª Generación)",
    para_que_sirve: "Tratamiento de infecciones bacterianas susceptibles: otitis media, infecciones de piel y tejidos blandos, infecciones del tracto urinario y faringoamigdalitis estreptocócica.",
    posologia: "Adultos: 250 a 500 mg cada 6 horas. Niños: 25 a 50 mg/kg/día divididos en 4 tomas. Duración habitual: 7 a 10 días.",
    contraindicaciones: "Hipersensibilidad a cefalosporinas. Precaución extrema (o evitar) en pacientes con alergia severa a penicilinas (riesgo de reactividad cruzada).",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "N/A",
    tips_venta: "Educación al paciente: Debe completar los 7-10 días de tratamiento aunque se sienta bien al tercer día. Suspender antes genera resistencia bacteriana. Tomar con o sin alimentos.",
    cross_selling: "Probióticos (Saccharomyces Boulardii) para prevenir diarrea asociada a antibióticos. Recordar tomar el probiótico con 3 horas de diferencia de la Cefalexina."
  },
  {
    nombre: "Doxiciclina 100 mg",
    principio_activo: "Doxiciclina Hiclato",
    categoria: "Antibiótico (Tetraciclina de amplio espectro)",
    para_que_sirve: "Infecciones del tracto respiratorio, acné severo, enfermedades de transmisión sexual (Clamidia, Sífilis en alérgicos a penicilina), y profilaxis de malaria.",
    posologia: "Adultos: 100 mg cada 12 horas el primer día, seguido de 100 mg una vez al día o 50 mg cada 12 horas. Tomar con un vaso lleno de agua.",
    contraindicaciones: "Embarazo y lactancia (afecta huesos y dientes del feto/bebé). Niños menores de 8 años (decoloración dental permanente). Insuficiencia hepática severa.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Prevención de Esofagitis: El paciente debe tomarla con al menos 200 ml de agua y NO acostarse durante al menos 30 minutos después, para evitar úlceras esofágicas. Provoca fotosensibilidad severa.",
    cross_selling: "Bloqueador solar FPS 50+ de uso obligatorio si el paciente va a exponerse al sol, ya que la piel se quema con facilidad extrema."
  },
  {
    nombre: "Terbinafina 250 mg",
    principio_activo: "Clorhidrato de Terbinafina",
    categoria: "Antifúngico Sistémico (Alilamina)",
    para_que_sirve: "Tratamiento de onicomicosis (hongos en uñas de manos y pies) y tiñas extensas que no responden a tratamiento tópico.",
    posologia: "Adultos: 250 mg una vez al día. Duración: 6 semanas para uñas de manos, 12 semanas para uñas de pies. Tomar con o sin alimentos.",
    contraindicaciones: "Insuficiencia hepática crónica o aguda. Precaución en insuficiencia renal (depuración < 50 ml/min).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Paciencia clínica: El crecimiento de la uña sana es lento. El paciente debe entender que el resultado estético final se verá meses después de terminar las pastillas. Requiere exámenes de hígado previos.",
    cross_selling: "Esmaltes antifúngicos tópicos (como apoyo), cortauñas de uso exclusivo para la uña afectada (para no contagiar otras) y talco antimicótico para zapatos."
  },
  {
    nombre: "Clotrimazol 1% Crema",
    principio_activo: "Clotrimazol",
    categoria: "Antifúngico Tópico (Imidazol)",
    para_que_sirve: "Tratamiento tópico de dermatofitosis (tiña corporal, cruris, pedis), candidiasis cutánea y pitiriasis versicolor.",
    posologia: "Aplicar una capa delgada sobre el área afectada y 2 cm alrededor, 2 a 3 veces al día. Duración: 2 a 4 semanas.",
    contraindicaciones: "Hipersensibilidad a imidazoles. No aplicar en los ojos. Primer trimestre de embarazo (bajo evaluación médica).",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Regla de aplicación: Continuar aplicando la crema durante 1 a 2 semanas DESPUÉS de que las lesiones hayan desaparecido visualmente para evitar recaídas. No cubrir con vendajes oclusivos.",
    cross_selling: "Polvos antimicóticos para calzar (si es tiña pedis), toallas de uso exclusivo y jabón de azufre o neutro."
  },
  {
    nombre: "Albendazol 400 mg",
    principio_activo: "Albendazol",
    categoria: "Antiparasitario Intestinal de Amplio Espectro",
    para_que_sirve: "Tratamiento de helmintiasis intestinales comunes: Oxiuriasis (oxiuros), Ascariasis, Tricuriasis y Uncinariasis.",
    posologia: "Dosis única de 400 mg (1 comprimido o 10 ml de suspensión) para la mayoría de las parasitosis. En estrongiloidiasis o teniasis se requieren 3 días consecutivos. Masticar el comprimido.",
    contraindicaciones: "Embarazo (teratogénico en animales). Precaución en pacientes con antecedentes de discrasias sanguíneas o enfermedad hepática.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Para que sea más efectivo contra los parásitos adultos, se recomienda administrarlo en ayunas o con una comida ligera. Si es para Oxiuros (que pica el ano de noche), se debe repetir la dosis a los 15 días.",
    cross_selling: "Suspensión de Albendazol (si el paciente es niño pequeño que no puede tragar pastillas), jabón de manos antibacterial."
  },
  {
    nombre: "Levonorgestrel 1.5 mg (PAE)",
    principio_activo: "Levonorgestrel",
    categoria: "Anticonceptivo Hormonal de Emergencia",
    para_que_sirve: "Prevención del embarazo tras relaciones sexuales sin protección o fallo del método anticonceptivo habitual (Anticoncepción de Emergencia).",
    posologia: "1 comprimido de 1.5 mg por vía oral lo antes posible. Eficacia máxima si se toma en las primeras 12 horas. Límite absoluto: 72 horas (3 días) post-coito.",
    contraindicaciones: "Embarazo confirmado (no interrumpe embarazos existentes). Sangrado vaginal anormal de origen desconocido.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Educación vital: NO es un método anticonceptivo regular, es de RESCATE. Si la paciente vomita antes de 2 horas, debe repetir la dosis. Puede alterar el ciclo menstrual (adelantarlo o atrasarlo).",
    cross_selling: "Test de embarazo (instruir que se lo haga en 3 semanas si su menstruación se retrasa más de 7 días), preservativos para uso inmediato."
  },
  {
    nombre: "Sildenafil 50 mg",
    principio_activo: "Citrato de Sildenafil",
    categoria: "Inhibidor de la Fosfodiesterasa tipo 5 (PDE5)",
    para_que_sirve: "Tratamiento de la disfunción eréctil. Facilita la erección solo ante estimulación sexual, relajando los vasos sanguíneos del pene.",
    posologia: "Dosis recomendada: 50 mg aproximadamente 1 hora antes de la actividad sexual. Puede ajustarse a 100 mg o reducirse a 25 mg según eficacia y tolerancia.",
    contraindicaciones: "ABSOLUTAMENTE CONTRAINDICADO en pacientes que usen nitratos (nitroglicerina para el corazón) por riesgo de hipotensión fatal. Cardiopatías inestables severas.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "El 'factor comida': Si el paciente lo toma después de una comida copiosa o muy grasosa, el efecto tardará mucho más en aparecer o será más débil. Lo ideal es en ayunas o con comida ligera.",
    cross_selling: "Ninguno directo por seguridad. Si el paciente usa pastillas para la próstata (Tamsulosina), advertir que puede marearse al levantarse (hipotensión ortostática)."
  },
  {
    nombre: "Tadalafil 5 mg",
    principio_activo: "Tadalafil",
    categoria: "Inhibidor de la Fosfodiesterasa tipo 5 (PDE5) - Acción Prolongada",
    para_que_sirve: "Disfunción eréctil (permite espontaneidad por su larga duración) y tratamiento de los signos y síntomas de la Hiperplasia Prostática Benigna (HPB).",
    posologia: "Para HPB o uso diario DE: 5 mg una vez al día, a la misma hora, sin importar las comidas. Para uso a demanda (10-20 mg): 30 min antes de la relación sexual.",
    contraindicaciones: "Uso concomitante con nitratos. Pacientes con infarto reciente (últimos 90 días), insuficiencia cardíaca inestable o hipotensión severa.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "La gran ventaja: A diferencia del Sildenafil, el Tadalafil permanece en el sistema hasta 36 horas. La dosis diaria de 5 mg también mejora los síntomas urinarios de la próstata agrandada.",
    cross_selling: "Evitar combinar con alfabloqueantes (como Doxazosina) sin supervisión estricta por riesgo de bajadas de presión."
  },
  {
    nombre: "Finasterida 5 mg",
    principio_activo: "Finasterida",
    categoria: "Inhibidor de la 5-alfa Reductasa",
    para_que_sirve: "Tratamiento y control de la Hiperplasia Prostática Benigna (HPB). Reduce el tamaño de la próstata, mejora el flujo urinario y disminuye el riesgo de retención aguda de orina.",
    posologia: "1 comprimido de 5 mg al día, con o sin alimentos. Los resultados clínicos (reducción de la próstata) pueden tardar de 3 a 6 meses en notarse.",
    contraindicaciones: "Mujeres y niños. Mujeres embarazadas NO deben manipular comprimidos triturados o rotos (riesgo de malformaciones en feto masculino).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Advertencia de seguridad: Las mujeres embarazadas o que puedan estarlo no deben tocar las pastillas de Finasterida (el principio activo se absorbe por la piel y afecta al feto).",
    cross_selling: "Si el paciente también tiene disfunción eréctil, el médico podría evaluar combinar con Tadalafil."
  },
  {
    nombre: "Mupirocina 2% Ungüento",
    principio_activo: "Mupirocina Cálcica",
    categoria: "Antibiótico Tópico",
    para_que_sirve: "Tratamiento de infecciones bacterianas de la piel altamente contagiosas como el impétigo, foliculitis, y heridas infectadas por Staphylococcus aureus (incluyendo MRSA).",
    posologia: "Aplicar una pequeña cantidad sobre el área afectada 3 veces al día durante 5 a 10 días. Puede cubrirse con gasa estéril.",
    contraindicaciones: "Hipersensibilidad a la mupirocina. No usar en áreas extensas de piel lesionada o en mucosas (ojos, boca) por riesgo de absorción sistémica del polietilenglicol.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Cadena de frío: Muchas marcas comerciales de Mupirocina requieren conservación en refrigerador (2°C a 8°C). Revisar la caja al recibirla del proveedor y al entregarla al paciente.",
    cross_selling: "Gasas estériles, micropore (tela adhesiva), jabón antibacterial para higiene de la zona."
  },
  {
    nombre: "Neomicina + Bacitracina Ungüento",
    principio_activo: "Sulfato de Neomicina + Bacitracina Zinc",
    categoria: "Antibiótico Tópico de Amplio Espectro",
    para_que_sirve: "Prevención y tratamiento de infecciones superficiales de la piel causadas por bacterias Gram positivas y Gram negativas en cortes, rasguños y quemaduras leves.",
    posologia: "Limpiar la zona y aplicar una capa fina de ungüento 1 a 3 veces al día.",
    contraindicaciones: "Hipersensibilidad a aminoglucósidos (neomicina). No aplicar en quemaduras extensas, heridas profundas o úlceras por decúbito avanzadas sin indicación médica.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Es el 'botiquín de primeros auxilios' por excelencia. Advertir que si la herida es profunda, muy sucia o tiene bordes irregulares, debe ir a urgencias para evaluar puntos o vacuna antitetánica.",
    cross_selling: "Suero fisiológico en monodosis para limpieza previa de la herida, curitas, vendas elásticas."
  },
  {
    nombre: "Ketoconazol 2% Champú",
    principio_activo: "Ketoconazol",
    categoria: "Antifúngico Tópico / Anticaspa",
    para_que_sirve: "Tratamiento de la dermatitis seborreica (caspa severa, descamación, prurito) y tiña del cuero cabelludo (tinea capitis).",
    posologia: "Aplicar sobre el cabello húmedo, masajear el cuero cabelludo y DEJAR ACTUAR de 3 a 5 minutos antes de enjuagar. Usar 2 veces por semana durante 2 a 4 semanas.",
    contraindicaciones: "Hipersensibilidad al ketoconazol. Evitar contacto con los ojos (irrita severamente).",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "El error más común: Usarlo como champú normal y enjuagar de inmediato. El medicamento necesita tiempo de contacto con el hongo. Si el paciente dice 'no me funcionó', pregúntale cómo lo usó.",
    cross_selling: "Acondicionadores hidratantes o reparadores, ya que el ketoconazol tiende a dejar el cabello muy reseco y áspero."
  },
  {
    nombre: "Permetrina 1% Loción",
    principio_activo: "Permetrina",
    categoria: "Antiparasitario Tópico (Escabicida / Pediculicida)",
    para_que_sirve: "Tratamiento de elección para la pediculosis (piojos) y escabiosis (sarna). Actúa por contacto paralizando el sistema nervioso de los parásitos.",
    posologia: "Piojos: Aplicar en cabello seco, dejar 10 min y enjuagar. Escabiosis: Aplicar de cuello a pies (incluyendo pliegues), dejar 8-14 horas (toda la noche) y bañarse.",
    contraindicaciones: "Hipersensibilidad a piretroides o crisantemos. Precaución en lactantes menores de 2 meses y embarazadas (evaluar riesgo/beneficio).",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "El secreto del éxito no es solo la loción, es el entorno: Toda la ropa de cama, toallas y ropa usada en los últimos 3 días debe lavarse con agua caliente (60°C) o sellarse en bolsas de plástico por 72 horas.",
    cross_selling: "Peine lendrera metálico de dientes finos, spray desinfectante para textiles/ambientes, champú con ácido acético (vinagre) para disolver el 'pegamento' de las liendres."
  },
  {
    nombre: "Ácido Fólico 1 mg",
    principio_activo: "Ácido Fólico (Vitamina B9)",
    categoria: "Vitamina / Antianémico",
    para_que_sirve: "Prevención de defectos del tubo neural en el feto (anencefalia, espina bífida) y tratamiento de anemias megaloblásticas por deficiencia de folatos.",
    posologia: "Prevención en embarazo: 0.4 a 1 mg al día, iniciando al menos 1 mes antes de la concepción y durante el primer trimestre. Tratamiento de anemia: Dosis según indicación médica.",
    contraindicaciones: "Anemia perniciosa no diagnosticada (enmascara el déficit de B12 permitiendo daño neurológico irreversible).",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Es la vitamina 'seguro de vida' para embarazadas. Si la paciente planea buscar un embarazo, debe empezar a tomarlo YA, no cuando se entere de que está embarazada, ya que el tubo neural se forma en las primeras 4 semanas.",
    cross_selling: "Sulfato Ferroso (el dúo dinámico para prevenir anemia en el embarazo), multivitamínicos prenatales."
  },
  {
    nombre: "Sulfato Ferroso 200 mg",
    principio_activo: "Sulfato Ferroso (equiv. a 60 mg de Hierro Elemental)",
    categoria: "Antianémico / Suplemento Mineral",
    para_que_sirve: "Prevención y tratamiento de la anemia ferropénica (por falta de hierro), común en embarazadas, niños en crecimiento, vegetarianos estrictos o personas con sangrado crónico.",
    posologia: "Tratamiento: 1 comprimido al día (o cada 2 días para mejor absorción y menos efectos gástricos). Preferiblemente en ayunas o con comidas ricas en Vitamina C.",
    contraindicaciones: "Hemocromatosis, anemias hemolíticas, úlcera péptica activa, enfermedad inflamatoria intestinal severa.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "Efectos esperados: Advertir al paciente que las heces se pondrán de color negro verdoso (es normal e inofensivo). Si causa mucho dolor de guata, sugerir tomarlo con el estómago lleno o en días alternos.",
    cross_selling: "Vitamina C (el ácido ascórbico multiplica por 3 la absorción del hierro). Evitar tomar junto con lácteos, café o té (bloquean la absorción)."
  },
  {
    nombre: "Tobramicina 0.3% Gotas Oftálmicas",
    principio_activo: "Tobramicina",
    categoria: "Antibiótico Oftálmico (Aminoglucósido)",
    para_que_sirve: "Tratamiento de infecciones bacterianas externas del ojo: conjuntivitis bacterianas, blefaritis, queratitis y dacriocistitis.",
    posologia: "1 a 2 gotas en el ojo afectado cada 4 a 8 horas. En infecciones severas, puede instilarse cada 1 a 2 horas las primeras 48 horas.",
    contraindicaciones: "Hipersensibilidad a aminoglucósidos o a otros componentes. Infecciones virales o fúngicas del ojo (no tiene efecto y puede empeorar).",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Técnica de aplicación: Lavarse bien las manos, tirar del párpado inferior hacia abajo, instilar la gota en el 'saco' sin que la punta del gotario toque el ojo o las pestañas (para no contaminar el frasco).",
    cross_selling: "Suero fisiológico en monodosis o agua destilada estéril para limpiar las 'lagañas' o secreciones antes de aplicar la gota."
  },
  {
    nombre: "Latanoprost 0.005% Gotas Oftálmicas",
    principio_activo: "Latanoprost",
    categoria: "Análogo de Prostaglandina (Antiglaucomatoso)",
    para_que_sirve: "Reducción de la presión intraocular elevada en pacientes con glaucoma de ángulo abierto o hipertensión ocular. Previene el daño al nervio óptico y la ceguera.",
    posologia: "1 gota en el ojo afectado una vez al día, preferentemente por la NOCHE. No exceder la dosis diaria (menos es más, más dosis reduce la eficacia).",
    contraindicaciones: "Hipersensibilidad al principio activo. Precaución en pacientes con historia de uveítis o edema macular quístico.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "Cadena de Frío Estricta: El frasco SIN ABRIR debe guardarse en el refrigerador (2-8°C). Una vez abierto, puede conservarse a temperatura ambiente (máx 25°C) pero solo por 28 días. ¡Marcar la fecha de apertura en la caja!",
    cross_selling: "Ninguno directo. El foco es la adherencia estricta: el glaucoma es asintomático hasta que se pierde la visión, por lo que el paciente no 'siente' que el medicamento funciona."
  }
];

// 🚀 4. BLOQUE III: ANTIBIÓTICOS INYECTABLES, PSICOTRÓPICOS, CARDIOVASCULARES Y HORMONAS (ACTUALIZADO)
export const BLOQUE_III = [
  {
    nombre: "Penicilina Benzatina 1.200.000 UI",
    principio_activo: "Penicilina G Benzatina",
    categoria: "Antibiótico de Depósito (Betalactámico)",
    para_que_sirve: "Tratamiento de la sífilis y profilaxis de la fiebre reumática. Su liberación lenta permite mantener niveles terapéuticos por 3 a 4 semanas.",
    presentaciones: "Frasco ampolla (Polvo para suspensión inyectable): 1.200.000 UI y 2.400.000 UI. Generalmente requiere dilución con agua para inyectables.",
    posologia: "Vía intramuscular profunda exclusivamente. Adultos: 1.200.000 a 2.400.000 UI en dosis única según indicación médica.",
    contraindicaciones: "Hipersensibilidad a las penicilinas; riesgo de shock anafiláctico.",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "N/A",
    tips_venta: "REACCIÓN ALÉRGICA: Preguntar siempre si el paciente se ha aplicado penicilina antes sin problemas. Si es la primera vez, el paciente debe esperar 30 minutos en el centro asistencial tras la inyección.",
    cross_selling: "Probióticos para la flora bacteriana y parches curativos de gran tamaño."
  },
  {
    nombre: "Fentermina 37.5 mg",
    principio_activo: "Fentermina Clorhidrato",
    categoria: "Anorexígeno (Tratamiento de la Obesidad)",
    para_que_sirve: "Manejo de la obesidad exógena a corto plazo en conjunto con dieta y ejercicio.",
    presentaciones: "Cápsulas / Comprimidos: 18.75 mg y 37.5 mg. Marcas comunes incluyen Sentis y Elvenir.",
    posologia: "Generalmente 1 unidad al día por la mañana, antes del desayuno. No exceder las 12 semanas de uso.",
    contraindicaciones: "Hipertensión arterial severa, glaucoma, hipertiroidismo y antecedentes de abuso de drogas.",
    condicion_venta: "Receta Cheque",
    lista_control: "Lista II",
    tips_venta: "INSOMNIO: Advertir que debe tomarse temprano; si se toma después de mediodía, es muy probable que el paciente no pueda dormir esa noche.",
    cross_selling: "Multivitamínicos para compensar la baja ingesta calórica y básculas digitales."
  },
  {
    nombre: "Bisoprolol 2.5 mg / 5 mg",
    principio_activo: "Bisoprolol Fumarato",
    categoria: "Antihipertensivo (Betabloqueador Selectivo)",
    para_que_sirve: "Hipertensión arterial e insuficiencia cardíaca crónica estable.",
    presentaciones: "Comprimidos Recubiertos: 1.25 mg, 2.5 mg, 5 mg y 10 mg. (Marcas: Concor, Bisocor).",
    posologia: "1 comprimido al día, preferentemente en la mañana. La dosis se ajusta según la frecuencia cardíaca objetivo.",
    contraindicaciones: "Bradicardia extrema, asma bronquial severa y bloqueo cardíaco de alto grado.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "NO SUSPENDER BRUSCAMENTE: El cese repentino puede causar taquicardia severa. Si el paciente olvida comprarlo, enfatizar la continuidad.",
    cross_selling: "Tensiómetros digitales de brazo y suplementos de Coenzima Q10."
  },
  {
    nombre: "Ácido Ursodeoxicólico 250 mg",
    principio_activo: "Ácido Ursodeoxicólico",
    categoria: "Hepatoprotector / Litolítico",
    para_que_sirve: "Disolución de cálculos biliares de colesterol y tratamiento de cirrosis biliar primaria.",
    presentaciones: "Cápsulas: 250 mg (Envases de 60 y 100 unidades). (Marca: Solvobil).",
    posologia: "8 a 10 mg/kg de peso al día, repartidos en 2 o 3 dosis.",
    contraindicaciones: "Cálculos calcificados, colecistitis aguda y obstrucción biliar.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "TRATAMIENTO LARGO: Explicar que los resultados no son inmediatos; los cálculos pueden tardar meses en disolverse.",
    cross_selling: "Protectores hepáticos naturales (Silimarina) y dietas libres de grasas saturadas."
  },
  {
    nombre: "Enoxaparina 60 mg / 80 mg",
    principio_activo: "Enoxaparina Sódica",
    categoria: "Anticoagulante (HBPM)",
    para_que_sirve: "Prevención de trombosis venosa profunda y tratamiento de síndromes coronarios agudos.",
    presentaciones: "Jeringas Prellenadas: 20 mg/0.2 mL, 40 mg/0.4 mL, 60 mg/0.6 mL y 80 mg/0.8 mL. (Marca: Clexane).",
    posologia: "Vía subcutánea profunda. La dosis se calcula por kg de peso y el objetivo clínico (profilaxis o tratamiento).",
    contraindicaciones: "Hemorragia activa, insuficiencia renal grave y antecedentes de trombocitopenia por heparina.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "LUGAR DE INYECCIÓN: Indicar que debe inyectarse en el abdomen, alternando el lado izquierdo y derecho cada día para evitar fibrosis local.",
    cross_selling: "Algodón, alcohol y contenedores de eliminación de agujas (punzocortantes)."
  },
  {
    nombre: "Bromazepam 3 mg",
    principio_activo: "Bromazepam",
    categoria: "Ansiolítico (Benzodiazepina)",
    para_que_sirve: "Tratamiento de la ansiedad severa y estados de agitación.",
    presentaciones: "Comprimidos: 1.5 mg, 3 mg y 6 mg (Cajas de 30 comprimidos). (Marca: Lexotanil).",
    posologia: "Dosis habitual: 1.5 a 3 mg hasta tres veces al día.",
    contraindicaciones: "Insuficiencia respiratoria, apnea del sueño y miastenia gravis.",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "Lista IV",
    tips_venta: "SUEÑO RESIDUAL: Advertir que puede causar somnolencia al día siguiente. No debe conducir vehículos hasta conocer su reacción al fármaco.",
    cross_selling: "Infusiones de hierbas relajantes (Melisa/Pasiflora) para apoyar la higiene del sueño."
  },
  {
    nombre: "Sitagliptina 100 mg",
    principio_activo: "Sitagliptina",
    categoria: "Antidiabético Oral (Inhibidor DPP-4)",
    para_que_sirve: "Control de la glucemia en pacientes con Diabetes Mellitus Tipo 2.",
    presentaciones: "Comprimidos Recubiertos: 25 mg, 50 mg y 100 mg (Marca: Januvia). Asociación con Metformina: 50/500, 50/850, 50/1000 mg (Marca: Crisomet o Janumet).",
    posologia: "100 mg una vez al día solo, o asociado a metformina según el esquema del médico.",
    contraindicaciones: "Diabetes Tipo 1 y cetoacidosis diabética.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "PESO NEUTRO: A diferencia de otros antidiabéticos, la sitagliptina no tiende a producir aumento de peso, lo cual es un beneficio para el paciente diabético.",
    cross_selling: "Máquinas medidoras de glucosa, lancetas y cremas para hidratación profunda de pies."
  },
  {
    nombre: "Tiamazol 5 mg / 10 mg / 20 mg",
    principio_activo: "Tiamazol (Metimazol)",
    categoria: "Antitiroideo",
    para_que_sirve: "Tratamiento del hipertiroidismo.",
    presentaciones: "Comprimidos: 5 mg, 10 mg y 20 mg (Envases de 50 o 100 unidades). (Marca: Thyrozol).",
    posologia: "Dosis inicial alta (30-40 mg) y mantenimiento de 5 a 15 mg diarios.",
    contraindicaciones: "Embarazo (primer trimestre) y antecedentes de trastornos sanguíneos graves.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "CONTROL DE SANGRE: Advertir que si el paciente presenta fiebre súbita o dolor de garganta persistente, debe suspenderlo y contactar a su médico (riesgo de baja de defensas).",
    cross_selling: "Protectores solares (el hipertiroidismo puede aumentar la sensibilidad cutánea) y lágrimas artificiales."
  },
  {
    nombre: "Juliette (Etinilestradiol / Clormadinona)",
    principio_activo: "Etinilestradiol 0.03 mg + Clormadinona Acetato 2 mg",
    categoria: "Anticonceptivo Hormonal Combinado",
    para_que_sirve: "Prevención del embarazo con beneficios adicionales en acné y seborrea.",
    presentaciones: "Comprimidos: Blíster calendario con 21 comprimidos activos. (Similar a marca Belara).",
    posologia: "1 comprimido al día durante 21 días, seguido de 7 días de descanso.",
    contraindicaciones: "Tabaquismo intenso en mayores de 35 años, antecedentes de trombosis y migraña con aura.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "ESTÉTICA: Explicar que la Clormadinona ayuda a reducir la grasa del cutis y el pelo, un efecto muy valorado por las usuarias jóvenes.",
    cross_selling: "Preservativos para protección contra ITS y jabones de higiene íntima con pH balanceado."
  },
  {
    nombre: "Hedera Helix Jarabe",
    principio_activo: "Extracto seco de hojas de Hedera helix",
    categoria: "Expectorante / Mucolítico de origen natural",
    para_que_sirve: "Tratamiento de los síntomas de enfermedades bronquiales y tos con flemas.",
    presentaciones: "Jarabe: 35 mg/5 ml (Frascos de 100 y 120 ml). (Marcas: Abrilar, Brontec). Gotas Orales: En concentraciones pediátricas.",
    posologia: "Adultos: 5 a 7.5 ml 3 veces al día. Niños mayores de 2 años: 2.5 ml 3 veces al día.",
    contraindicaciones: "Hipersensibilidad a la hiedra. No recomendado en menores de 2 años sin supervisión.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "NATURAL: Ideal para pacientes que buscan alternativas no químicas para la tos productiva. No contiene azúcar en la mayoría de sus versiones comerciales (apto para diabéticos).",
    cross_selling: "Caramelos de miel y jengibre para suavizar la garganta y termómetros."
  },
  {
    nombre: "Midazolam 7.5 mg / 15 mg",
    principio_activo: "Midazolam",
    categoria: "Inductor del sueño / Sedante (Benzodiazepina)",
    para_que_sirve: "Tratamiento a corto plazo del insomnio grave y sedación pre-operatoria.",
    presentaciones: "Comprimidos Recubiertos: 7.5 mg y 15 mg. (Marca: Dormonid). Solución Inyectable: 5 mg/5 ml y 50 mg/10 ml (Uso hospitalario).",
    posologia: "Adultos: 7.5 a 15 mg inmediatamente antes de acostarse. Efecto muy rápido.",
    contraindicaciones: "Insuficiencia respiratoria severa y glaucoma de ángulo estrecho.",
    condicion_venta: "Receta Médica Retenida",
    lista_control: "Lista IV",
    tips_venta: "AMNESIA: Advertir que puede causar 'olvidos' de lo que se hizo justo antes de dormir. El paciente debe estar ya en pijama y listo para dormir al tomarlo.",
    cross_selling: "Tapones de oídos de silicona y antifaces para oscuridad total."
  },
  {
    nombre: "Mesalazina 500 mg / 1000 mg",
    principio_activo: "Mesalazina (5-ASA)",
    categoria: "Antiinflamatorio Intestinal Local",
    para_que_sirve: "Tratamiento de la Colitis Ulcerosa y enfermedad de Crohn.",
    presentaciones: "Comprimidos / Tabletas: 500 mg y 1000 mg (Liberación retardada o prolongada). Supositorios: 500 mg y 1000 mg. (Marca: Pentasa). Enema: Para aplicación rectal local.",
    posologia: "Variable. Mantenimiento suele ser 1.5 a 2 g al día. En crisis puede ser mucho mayor.",
    contraindicaciones: "Hipersensibilidad a los salicilatos (Aspirina) e insuficiencia renal grave.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "FORMA DE TOMA: Los comprimidos de liberación prolongada no deben partirse ni masticarse, deben tragarse enteros para que lleguen al colon.",
    cross_selling: "Suplementos de Hierro y multivitaminas (la inflamación intestinal suele causar mala absorción)."
  },
  {
    nombre: "Ácido Tranexámico 500 mg",
    principio_activo: "Ácido Tranexámico",
    categoria: "Antifibrinolítico / Hemostático",
    para_que_sirve: "Control de hemorragias, especialmente en odontología, cirugía y menstruaciones abundantes.",
    presentaciones: "Comprimidos: 500 mg (Cajas de 20 y 30 unidades). (Marca: Espercil). Ampollas (Inyectable): 500 mg/5 mL (Uso clínico y odontológico).",
    posologia: "Adultos: 1 g (2 comp.) cada 8 horas mientras dure el sangrado intenso.",
    contraindicaciones: "Antecedentes de trombosis arterial o venosa y riesgo de convulsiones.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "EXTRACCIONES DENTALES: Si el dentista lo indica tras una cirugía, se puede disolver el contenido de una ampolla en un poco de agua y hacer enjuagues suaves sin tragar.",
    cross_selling: "Gasa estéril y suplementos de Hierro elemental."
  },
  {
    nombre: "Mintalub (Salicilato / Mentol)",
    principio_activo: "Salicilato de Metilo + Mentol Natural",
    categoria: "Analgésico de uso local / Rubefaciente",
    para_que_sirve: "Alivio de dolores musculares, articulares y torceduras.",
    presentaciones: "Crema / Gel: Pomo de 35 g. Pomada: Formatos de 15 g y 30 g.",
    posologia: "Aplicar en la zona afectada 3 a 4 veces al día con un masaje suave.",
    contraindicaciones: "No aplicar en heridas abiertas, mucosas o piel irritada. Alergia a salicilatos.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "EFECTO CALOR: Indicar que el área puede ponerse roja y caliente, es normal por el aumento de flujo sanguíneo que ayuda a desinflamar. Lavarse las manos tras usarlo para no pasarse los dedos por los ojos.",
    cross_selling: "Vendas elásticas (cobán) y compresas de gel frío/calor."
  },
  {
    nombre: "Lisinopril 20 mg",
    principio_activo: "Lisinopril",
    categoria: "Antihipertensivo (IECA)",
    para_que_sirve: "Hipertensión arterial e insuficiencia cardíaca.",
    presentaciones: "Comprimidos: 5 mg, 10 mg y 20 mg (Cajas de 30 comprimidos). (Marca: Miliser).",
    posologia: "Dosis habitual: 10 a 20 mg en una sola toma diaria, siempre a la misma hora.",
    contraindicaciones: "Embarazo (especialmente 2º y 3º trimestre) y antecedentes de angioedema.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "TOS SECA: Es el efecto secundario más típico de este grupo (IECA). Si el paciente desarrolla una tos persistente sin resfrío, debe mencionarlo a su médico para cambiar el fármaco.",
    cross_selling: "Tensiómetros digitales y sal de potasio (si el médico no la restringe)."
  },
  {
    nombre: "Dicloxacilina 500 mg",
    principio_activo: "Dicloxacilina Sódica",
    categoria: "Antibiótico (Penicilina Antiestafilocócica)",
    para_que_sirve: "Infecciones de la piel (como celulitis o abscesos) causadas por estafilococos.",
    presentaciones: "Cápsulas: 500 mg. Suspensión Oral: 250 mg/5 ml (Para uso pediátrico).",
    posologia: "500 mg cada 6 horas (4 veces al día). Debe tomarse 1 hora antes de las comidas.",
    contraindicaciones: "Alergia a penicilinas y cefalosporinas.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "ESTÓMAGO VACÍO: La comida reduce drásticamente su absorción. Enfatizar que se tome lejos de las comidas para que cure la infección de la piel rápido.",
    cross_selling: "Cremas antibióticas tópicas (Mupirocina) y jabones antisépticos."
  },
  {
    nombre: "Mebendazol 100 mg",
    principio_activo: "Mebendazol",
    categoria: "Antiparasitario",
    para_que_sirve: "Infecciones por oxiuros (pillo), lombrices y otros parásitos intestinales.",
    presentaciones: "Comprimidos Masticables: 100 mg. Suspensión Oral: 100 mg/5 ml (Frascos de 30 ml).",
    posologia: "Generalmente 100 mg dos veces al día por 3 días. Para oxiuros suele ser dosis única y repetir en 2 semanas.",
    contraindicaciones: "Embarazo y lactancia. Niños menores de 2 años.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "TRATAMIENTO FAMILIAR: Si un niño tiene parásitos, todos en la casa deben tomar el medicamento, ya que los huevos del parásito se propagan fácilmente en sábanas y toallas.",
    cross_selling: "Alcohol gel para manos y consejos de higiene profunda en el hogar."
  },
  {
    nombre: "Piridostigmina 60 mg",
    principio_activo: "Bromuro de Piridostigmina",
    categoria: "Inhibidor de la Colinesterasa",
    para_que_sirve: "Tratamiento de la Miastenia Gravis (debilidad muscular severa).",
    presentaciones: "Comprimidos / Tabletas: 60 mg (Envases de 20 y 30 unidades). (Marca: Mestinon, Diluxen).",
    posologia: "Dosis muy individualizada. Habitualmente 60 mg varias veces al día (cada 4 a 6 horas).",
    contraindicaciones: "Obstrucción mecánica intestinal o del tracto urinario.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "HORARIO ESTRICTO: Es vital que el paciente no se salte las dosis, ya que de esto depende su fuerza muscular para respirar y tragar.",
    cross_selling: "Suplementos nutricionales líquidos para pacientes con dificultad para masticar."
  },
  {
    nombre: "Melatonina 3 mg",
    principio_activo: "Melatonina",
    categoria: "Inductor del sueño (Hormona natural)",
    para_que_sirve: "Regulación del ciclo sueño-vigilia, insomnio en adultos y jet-lag.",
    presentaciones: "Cápsulas / Comprimidos: 3 mg y 5 mg (Cajas de 30 y 60 unidades). (Marca: Somno).",
    posologia: "1 comprimido 30 a 60 minutos antes de ir a dormir.",
    contraindicaciones: "Hipersensibilidad al principio activo; no recomendada en embarazo sin consulta médica.",
    condicion_venta: "Venta Directa",
    lista_control: "N/A",
    tips_venta: "SIN PANTALLAS: La melatonina funciona mejor si tras tomarla el paciente apaga las luces y deja de usar el celular, ya que la luz bloquea su efecto natural.",
    cross_selling: "Infusiones nocturnas y suplementos de Magnesio."
  },
  {
    nombre: "Doxazosina 4 mg",
    principio_activo: "Doxazosina Mesilato",
    categoria: "Vasodilatador / Bloqueador Alfa-1",
    para_que_sirve: "Hiperplasia prostática benigna (dificultad para orinar) e hipertensión arterial.",
    presentaciones: "Comprimidos: 2 mg y 4 mg (Envases de 30 unidades). (Marca: Cardura).",
    posologia: "Habitualmente 2 a 4 mg una vez al día.",
    contraindicaciones: "Hipersensibilidad a las quinazolinas y antecedentes de hipotensión ortostática.",
    condicion_venta: "Receta Médica",
    lista_control: "N/A",
    tips_venta: "PRIMERA DOSIS: Recomendar al paciente tomar la primera dosis justo antes de acostarse, ya que puede producir un mareo fuerte o caída de presión al ponerse de pie (efecto de primera dosis).",
    cross_selling: "Suplementos de Saw Palmetto y protectores para incontinencia leve si fuera necesario."
  }
];