export const level7 = {
  id: 7,
  title: "Nivel 7: Examen Global SEREMI",
  icon: "Trophy",
  timeLimit: 3600, // 60 minutos
  passingScore: 24, // 60% de 40 preguntas
  medal: "Certificación Pro",
  description: "El desafío final. 40 preguntas de todas las áreas.",
  questions: [
    { text: "¿Quién dirige la farmacia?", options: ["Auxiliar", "Dueño", "Químico Farmacéutico", "Vendedor"], correctIndex: 2, studyGuide: "D.466" },
    { text: "Estrella Verde indica:", options: ["Estupefaciente", "Psicotrópico", "Venta Directa", "Antibiótico"], correctIndex: 1, studyGuide: "D.405" },
    { text: "Estrella Roja indica:", options: ["Estupefaciente", "Psicotrópico", "Venta Directa", "Vitamina"], correctIndex: 0, studyGuide: "D.404" },
    { text: "1 ml equivale a:", options: ["10 gotas", "15 gotas", "20 gotas", "30 gotas"], correctIndex: 2, studyGuide: "Posología" },
    { text: "¿Qué es la Canela?", options: ["Incentivo económico prohibido", "Saborizante", "Descuento legal", "Bono de colación"], correctIndex: 0, studyGuide: "Ley 20.724" },
    { text: "Rango temperatura refrigerador:", options: ["0-5°C", "2-8°C", "8-25°C", "Menos 0°C"], correctIndex: 1, studyGuide: "D.3" },
    { text: "Receta Clonazepam:", options: ["Simple", "Retenida", "Cheque", "Verbal"], correctIndex: 1, studyGuide: "D.405" },
    { text: "Receta Morfina:", options: ["Simple", "Retenida", "Cheque", "Verbal"], correctIndex: 2, studyGuide: "D.404" },
    { text: "Validez Receta Cheque:", options: ["30 días", "60 días", "90 días", "6 meses"], correctIndex: 0, studyGuide: "D.404" },
    { text: "¿Quién autoriza al auxiliar?", options: ["ISP", "SEREMI", "Minsal", "Municipalidad"], correctIndex: 1, studyGuide: "D.466" },
    { text: "¿Qué es bioequivalencia?", options: ["Igual precio", "Mismo efecto terapéutico certificado", "Mismo color", "Mismo envase"], correctIndex: 1, studyGuide: "D.3" },
    { text: "¿Puede un almacén farmacéutico hacer recetas magistrales?", options: ["Sí", "No, prohibido", "Solo cremas", "Solo si hay DT"], correctIndex: 1, studyGuide: "D.466" },
    { text: "Color receta cheque farmacia:", options: ["Café", "Rojo", "Amarillo", "Verde"], correctIndex: 2, studyGuide: "D.404" },
    { text: "Lista I de psicotrópicos:", options: ["Prohibidos (LSD)", "Benzodiazepinas", "Anfetaminas", "Barbitúricos"], correctIndex: 0, studyGuide: "D.405" },
    { text: "1 cucharadita de té:", options: ["2.5ml", "5ml", "10ml", "15ml"], correctIndex: 1, studyGuide: "Posología" },
    { text: "¿Dónde debe ir el precio?", options: ["En el sistema", "En el envase", "En un cartel", "No se pone"], correctIndex: 1, studyGuide: "Ley 20.724" },
    { text: "FEFO significa:", options: ["Primero vence, primero sale", "Primero entra, primero sale", "Último entra, primero sale", "Al azar"], correctIndex: 0, studyGuide: "D.3" },
    { text: "Requisito escolaridad auxiliar:", options: ["8° Básico", "4° Medio", "Técnico", "Universitario"], correctIndex: 1, studyGuide: "D.466" },
    { text: "¿Quién despacha estupefacientes?", options: ["Cualquiera", "El DT", "El auxiliar", "El cajero"], correctIndex: 1, studyGuide: "D.404" },
    { text: "¿Qué es fraccionamiento?", options: ["Vender la caja", "Vender dosis exacta", "Vender al por mayor", "Regalar muestras"], correctIndex: 1, studyGuide: "Ley 20.724" },
    { text: "Validez receta retenida psicotrópicos:", options: ["30 días", "60 días", "6 meses", "1 año"], correctIndex: 0, studyGuide: "D.405" },
    { text: "Codeína 10mg requiere:", options: ["Receta Simple", "Retenida", "Cheque", "Directa"], correctIndex: 0, studyGuide: "D.404" },
    { text: "Codeína 40mg requiere:", options: ["Simple", "Retenida", "Cheque", "Directa"], correctIndex: 1, studyGuide: "D.404" },
    { text: "Codeína 80mg requiere:", options: ["Simple", "Retenida", "Cheque", "Directa"], correctIndex: 2, studyGuide: "D.404" },
    { text: "Registro ISP F-1234 corresponde a:", options: ["Fármaco", "Cosmético", "Biológico", "Alimento"], correctIndex: 0, studyGuide: "D.3" },
    { text: "¿Qué es el Formulario Nacional de Medicamentos?", options: ["Un libro de reclamos", "La nómina de medicamentos esenciales", "Una lista de precios máxima", "Un recetario magistral"], correctIndex: 1, studyGuide: "Ley de Fármacos" },
    { text: "Por regla general, la venta de antibióticos sistémicos (como Amoxicilina) requiere:", options: ["Venta Directa", "Receta Médica Simple", "Receta Médica Retenida", "Receta Cheque"], correctIndex: 1, studyGuide: "D.3" },
    { text: "¿Qué leyenda obligatoria debe llevar una muestra médica?", options: ["Uso institucional", "Muestra médica prohibida su venta", "Venta exclusiva farmacias", "Uso intrahospitalario"], correctIndex: 1, studyGuide: "D.3" },
    { text: "Forma farmacéutica adecuada para un paciente con dificultad para tragar comprimidos:", options: ["Solución líquida", "Cápsula dura", "Píldora recubierta", "Comprimido ranurado"], correctIndex: 0, studyGuide: "Manual de Procedimientos" },
    { text: "¿Qué vía de administración permite una absorción más rápida en el organismo?", options: ["Vía oral", "Vía tópica", "Vía intravenosa", "Vía oftálmica"], correctIndex: 2, studyGuide: "Manual de Procedimientos" },
    { text: "Temperatura ambiente controlada estándar para almacenar medicamentos:", options: ["0 a 5°C", "15 a 25°C", "2 a 8°C", "Más de 30°C"], correctIndex: 1, studyGuide: "D.3" },
    { text: "¿Quién es el único responsable legal de llevar los libros de controlados?", options: ["El auxiliar de farmacia", "El Químico Farmacéutico (DT)", "El dueño del establecimiento", "Cualquier empleado"], correctIndex: 1, studyGuide: "D.404 / 405" },
    { text: "La sigla DCI en un medicamento significa:", options: ["Dosis Clínica Inicial", "Denominación Común Internacional", "Distribución Central Interna", "Dosis Común Internacional"], correctIndex: 1, studyGuide: "Ley 20.724" },
    { text: "¿Están obligadas las farmacias a disponer permanentemente de un Petitorio Mínimo?", options: ["Sí, siempre", "No, es opcional", "Solo cuando están de turno", "Solo las farmacias independientes"], correctIndex: 0, studyGuide: "D.466" },
    { text: "¿Quién determina los turnos que deben cumplir las farmacias?", options: ["La SEREMI de Salud", "La municipalidad", "El dueño de la farmacia", "Carabineros"], correctIndex: 0, studyGuide: "D.466" },
    { text: "¿Cuál de las siguientes es una función permitida del Auxiliar de Farmacia?", options: ["Diagnosticar a los pacientes", "Modificar las recetas médicas", "Dispensar bajo supervisión del Químico Farmacéutico", "Vender psicotrópicos sin receta"], correctIndex: 2, studyGuide: "D.466 / Manual" },
    { text: "¿Qué letra antecede al número de registro en el ISP de un producto cosmético?", options: ["F", "B", "C", "A"], correctIndex: 2, studyGuide: "D.3" },
    { text: "1 cucharada sopera equivale aproximadamente a:", options: ["5 ml", "10 ml", "15 ml", "20 ml"], correctIndex: 2, studyGuide: "Posología" },
    { text: "¿Qué profesionales están legalmente habilitados para emitir recetas médicas de uso humano en Chile?", options: ["Solo Médicos", "Médicos, Cirujano Dentistas y Matronas", "Enfermeras y Médicos", "Químicos Farmacéuticos"], correctIndex: 1, studyGuide: "D.466" },
    { text: "Si un fármaco es fotosensible (debe protegerse de la luz), su envase primario ideal es:", options: ["Transparente", "Plástico delgado transparente", "De color ámbar u opaco", "De vidrio común"], correctIndex: 2, studyGuide: "Manual de Procedimientos" }
  ]
};